<?php

namespace Rafaelogic\CodeSnoutr\Actions\IssueActions;

use Rafaelogic\CodeSnoutr\Contracts\Issues\IssueActionInterface;
use Rafaelogic\CodeSnoutr\Models\Issue;
use Rafaelogic\CodeSnoutr\Models\Setting;
use Rafaelogic\CodeSnoutr\Services\AI\AiFixGenerator;
use Illuminate\Support\Facades\Log;

class GenerateAiFixAction implements IssueActionInterface
{
    protected AiFixGenerator $aiFixGenerator;

    public function __construct(AiFixGenerator $aiFixGenerator)
    {
        $this->aiFixGenerator = $aiFixGenerator;
    }

    public function execute(Issue $issue): array
    {
        try {
            if (!$this->canExecute($issue)) {
                return [
                    'success' => false,
                    'message' => 'AI is not configured or issue already has a fix',
                    'data' => null
                ];
            }

            $result = $this->aiFixGenerator->generateFix($issue);
            
            if ($result['success']) {
                // Parse the JSON response to extract metadata
                $parsedData = $this->parseAiResponse($result['content']);
                
                $issue->update([
                    'ai_fix' => $result['content'], // Store raw JSON for AutoFixService
                    'ai_explanation' => $parsedData['explanation'] ?? 'Generated by AI',
                    'ai_confidence' => $parsedData['confidence'] ?? 0.75
                ]);
                
                return [
                    'success' => true,
                    'message' => 'AI fix suggestion generated successfully!',
                    'data' => [
                        'issueId' => $issue->id,
                        'filePath' => $issue->file_path,
                        'aiFix' => $result['content'],
                        'confidence' => $result['confidence'] ?? 0.75
                    ]
                ];
            }

            return [
                'success' => false,
                'message' => $result['error'] ?? 'Failed to generate AI fix',
                'data' => null
            ];

        } catch (\Exception $e) {
            Log::error('AI fix generation failed: ' . $e->getMessage());
            return [
                'success' => false,
                'message' => 'An error occurred while generating AI fix. Please try again.',
                'data' => null
            ];
        }
    }

    public function getDescription(): string
    {
        return 'Generate AI-powered fix suggestion';
    }

    public function canExecute(Issue $issue): bool
    {
        return $this->isAiConfigured() && 
               empty($issue->ai_fix) && 
               !$issue->fixed;
    }

    protected function isAiConfigured(): bool
    {
        $aiEnabled = Setting::getValue('ai_enabled', false);
        $apiKey = Setting::getOpenAiApiKey();
        
        return $aiEnabled && !empty($apiKey);
    }

    /**
     * Parse AI response to extract metadata while preserving raw JSON
     */
    protected function parseAiResponse(string $content): array
    {
        // Try to parse as JSON
        $jsonData = json_decode(trim($content), true);
        
        if (json_last_error() === JSON_ERROR_NONE && is_array($jsonData)) {
            return [
                'explanation' => $jsonData['explanation'] ?? 'AI-generated fix',
                'confidence' => $jsonData['confidence'] ?? 0.75,
                'safe_to_automate' => $jsonData['safe_to_automate'] ?? false,
            ];
        }

        // Fallback for non-JSON responses
        return [
            'explanation' => 'AI-generated fix',
            'confidence' => 0.75,
            'safe_to_automate' => false,
        ];
    }
}